import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import Headers from "../components/header";
import Footer from "../components/footer";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Tech With Masood",
  description: "Generated by Tech With Masood",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={raleway.className}>
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
